version: '3.8'

services:
  redis-node1:
    image: redis:latest
    container_name: redis-node1
    ports:
      - "6379:6379"
    volumes:
      - redis_node1_data:/data
    command: >
      redis-server --requirepass ${REDIS_PASSWORD}
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --appendfilename appendonly.aof

  redis-node2:
    image: redis:latest
    container_name: redis-node2
    ports:
      - "6380:6379"
    volumes:
      - redis_node2_data:/data
    command: >
      redis-server --requirepass ${REDIS_PASSWORD}
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --appendfilename appendonly.aof

  redis-node3:
    image: redis:latest
    container_name: redis-node3
    ports:
      - "6381:6379"
    volumes:
      - redis_node3_data:/data
    command: >
      redis-server --requirepass ${REDIS_PASSWORD}
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --appendfilename appendonly.aof

volumes:
  redis_node1_data:
    driver: local
  redis_node2_data:
    driver: local
  redis_node3_data:
    driver: local


#  starting
#docker docker-compose up -d

#  creating cluster
#docker exec -it redis-node1 redis-cli --cluster create \
#172.22.0.4:6379 \
#172.22.0.3:6379 \
#172.22.0.2:6379 \
#--cluster-replicas 0 \
#-a admin_125



